spring:
  application:
    name:questionnaire-backend
  datasource:
    url: jdbc:mysql://localhost:3306/mobile?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  session:
    timeout: 86400